title: Katherine Ellis for CCS
description: Katherine Ellis for Campus Chief Steward of UE local 1122 NUGW
theme: just-the-docs

url: https://Katherine-E.github.io/Katherine-Ellis-Campaign-For-Campus-Chief-Steward
